# -*- coding: utf-8 -*-
"""Forecast Study for PLMS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iPy2PIHEUKBgmYlZF_Qe3k0JG41FnxnR
"""

import pandas as pd
from fbprophet import Prophet

url_sales = 'https://raw.githubusercontent.com/facebook/prophet/master/examples/example_retail_sales.csv'
df = pd.read_csv(url_sales)

# Prophet Model
m = Prophet()
m.fit(df)

future = m.make_future_dataframe(periods=365)

forecast = m.predict(future)
# forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(36)

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

fig1 = m.plot(forecast)

fig2 = m.plot_components(forecast)